apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: gcr.io/visualdb-1046/kubequeue
          imagePullPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: workers
